//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumnosCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string NombreAlumno { get; set; }
        public string ApellidoAlumno { get; set; }
        public int Edad { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> CodCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
